// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VotingBoat.Database;

namespace VotingBoat.Migrations
{
    [DbContext(typeof(VoteDbContext))]
    [Migration("20200211181738_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1");

            modelBuilder.Entity("VotingBoat.Database.VoteMessage", b =>
                {
                    b.Property<ulong>("VoteMessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("VoteUserIds")
                        .HasColumnType("TEXT");

                    b.HasKey("VoteMessageId");

                    b.ToTable("VoteMessages");
                });
#pragma warning restore 612, 618
        }
    }
}
